### ISSUE TITLE
Planejamento

### ISSUE THREAD

**Issue by Anne-Ribeiro** [Anne-Ribeiro/2emia-projeto#6]
Anne, Carol, Mateus, Julie, Heloisa e Maria Clara.

**Comment by Anne-Ribeiro** [comment]
- [x] GitHub
- [x] Briefing
- [x] Estrutura do site

**Comment by habdig7oficial** [comment]
Beleza tudo feito agora temos que fazer o design

**Comment by habdig7oficial** [comment]
Planejamento da AC1 concluído va para inssue de layout para o próximo passo.
